export const products = [
  {
    id: "kb-001",
    name: "Ginger Bloom",
    price: 4.5,
    image: "/images/ginger-bloom.svg",
    category: "Spiced",
    description: "Raw ginger + turmeric. A warm, fiery finish.",
  },
  {
    id: "kb-002",
    name: "Wild Hibiscus",
    price: 5.0,
    image: "/images/wild-hibiscus.svg",
    category: "Floral",
    description: "Tart hibiscus steeped with rose petals.",
  },
  {
    id: "kb-003",
    name: "Elderflower Fizz",
    price: 5.0,
    image: "/images/elderflower-fizz.svg",
    category: "Floral",
    description: "Delicate elderflower, extra dry and sparkling.",
  },
  {
    id: "kb-004",
    name: "Charcoal Mint",
    price: 5.5,
    image: "/images/charcoal-mint.svg",
    category: "Herbal",
    description: "Activated charcoal cut with cooling garden mint.",
  },
  {
    id: "kb-005",
    name: "Blood Orange",
    price: 4.75,
    image: "/images/blood-orange.svg",
    category: "Citrus",
    description: "Pressed blood orange, bright and just a little bitter.",
  },
  {
    id: "kb-006",
    name: "Green Matcha",
    price: 5.75,
    image: "/images/green-matcha.svg",
    category: "Herbal",
    description: "Stone-ground matcha whisked into a grassy brew.",
  },
]